name: drecvmenv
channels:
  - conda-forge
dependencies:
  - python=3.9.12
  - anaconda=2022.05
  - prov=2.0.0
  - pydot=1.4.2
  - numpy=1.21.5
  - pandas=1.4.2
  - seaborn=0.11.2
  - matplotlib=3.5.1
  - plotly=5.6.0